"Filed out from Dolphin Smalltalk 7"!

Object subclass: #ShadowCompiledMethod
	instanceVariableNames: 'methodClass selector owningPackage'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ShadowCompiledMethod guid: (GUID fromString: '{03fb856d-c777-4d8d-8c08-aaf7f1d526cb}')!
ShadowCompiledMethod comment: ''!
!ShadowCompiledMethod categoriesForClass!Kernel-Objects! !
!ShadowCompiledMethod methodsFor!

methodClass
	^methodClass!

methodClass: anObject
	methodClass := anObject!

owningPackage
	^owningPackage!

owningPackage: anObject
	owningPackage := anObject!

selector
	^selector!

selector: anObject
	selector := anObject! !
!ShadowCompiledMethod categoriesFor: #methodClass!accessing!private! !
!ShadowCompiledMethod categoriesFor: #methodClass:!accessing!private! !
!ShadowCompiledMethod categoriesFor: #owningPackage!accessing!private! !
!ShadowCompiledMethod categoriesFor: #owningPackage:!accessing!private! !
!ShadowCompiledMethod categoriesFor: #selector!accessing!private! !
!ShadowCompiledMethod categoriesFor: #selector:!accessing!private! !

